### ISSUE TITLE
Unexpected U-turn near the toll booth on this toll road in Illinois

### ISSUE THREAD

**Issue by rmglennon** [valhalla/thor#221]
Southeast of Dixon, IL, there is a toll booth on the Ronald Reagan Memorial Tollway that has a straight-ahead lane used for electronic toll payment (Way: Ronald Reagan Memorial Tollway (38856926)) and a side lane for cash.

On certain, longer routes through this booth, Valhalla suggested making a U-Turn on the side lane. I wasn't able to get the U-Turn if the route ended at the next exit (such as "lat":41.8281,"lon":-89.4758). The differences in the tags between these ways are speeds and and number of lanes.

![image](https://cloud.githubusercontent.com/assets/4380498/9511900/7a05edf2-4c30-11e5-9b73-426c924f2bde.png)

JSON:
valhalla.mapzen.com/route?json={"locations":[{"lat":41.9067,"lon":-89.0688},{"lat":41.5893,"lon":-90.5715}],"costing":"auto"}&api_key=

Response:
{"trip":{"status":0,"status_message":"Found route between points","legs":[{"shape":"w_x|nAvxh{hDhv@]xl@OhjA\\|JvCtJ]jL]vg@gDpLOh\\M?hMhCnRxM|~@lEfXrE|TdFjV`HdZrF|T|Ib[`IfXfH~SjGrPhGdPnI~SvInS|m@xtA~b@`|@tqBf{EphHvzPj`@ngAln@xrCln@nlEtcAfoH|DbZfiDx}U`yBriO~C|TbmCfnRr|B~uOfm@pxCbgCngIxl@hjBtbA~bDjeEh}MrgCruMd_@fjBvdC|yM`jBv`Kbz@xqEh{Ivle@ha@rbChrHti`@nh@d`C`xMz_f@z~@fhDxmC~{JjlLbsb@lZjiAxp@xsB`kA`xCthAbmC``AxsBzhFrlLd|BjcFtZhw@pV~{@|TjjAzKj_AxG~eAlA~xVj@|}Jt@tkUNhtAz@toRMtkB?`jPe@xoO?zeD?r`Wj@tsNFj~J?|nW]jhBob@xmPgE~{AsE~oBOjpErAfkA|IfrNmD}gA{AgiD}@mpBUsmCz_@xoXt@~{AUx_B{F`eBiHfkAmZxrCia@pcDib@zyD_DnfBt@flAbG~fAfNtmA|Nxu@nc@rbCbjAbrGbLvl@rt@`bEpk@t_DveBxtJnD~SrQpeArUrnAlJ~h@xR`fAzUtvAz[lhAdc@ngAd_@fw@zo@peA~jBlqC~|@fvAntC|mErj@l}@vw@fwAjp@~eBrxAxzEhfAvrDf_CxbInsC`pJboA~lErnAthEzbC|hI`v@dwBpk@tmAfkBbvCvdCvhDdqCvsDpoAbcBxsBxsCjmBpwCpq@`zAdt@tkCrVtaBnWtiEjf@pqHti@vxIb[b_E`\\jqCj[rbCz[bdB`zAl_HxbDt}Nre@`zB`yBx_KzlBjtIzmBvxIlPzhAvRlrApWhhDxBdbBsAtzGGvc@sArhFgCdrFz@tiEjL`dBxRvlAjt@~cC`w@xuA|{AdlB`pAlgBzLtOf]td@vdCr`DbxBxrCpdBv_Cf}@ngApu@jsAtOb[nTpf@jPrp@~Xj}AhM~{AbFtvB]~|@W|h@?`_HUjtRd@hxZ?hgDFxdG\\hpEe@lzDOtDEtZD`q@zAzaQl@rwKUbcUr@`_PjAfvTMdtMO|qBgCjrBuKvjB{ZpnCmZdaBkdAnkFeaCpyLokAn_Gi`AzyEmcAd}EaX`qA_XbxAoNnr@{[|fB_S~|@}T~|@e@hCoSzt@kQdn@_Nja@skDrmKi\\taB_DtmA{Bzt[yAnwN?pwDe@hoXnHbxBpMtxAtTvuAha@rcBp]tbA~a@j`Az[vl@l|Bj|Cj`I`dKjmBxsC`uAv_Cz`@~{@dbBb`EjfCtqGvdD`qIbaCvdGllBt}ExoB|bFliNv`^pcB~aEt~@f_Dbj@djD~NhhC~CttDbBxuRlEveYTto@t@xk@zAnr@~Bzi@pCpg@vCj`@lEre@lEvb@di@nxD`l@`wDfoCxwQ`RflArqDt`VtlAddIhpAlsIfcEfqX`G|^ze@j|ChWfkB~I`g@`fEjyXplDbmUnaA`gHhMzhBpGpnB{@ftMT|xDfJ~yCjVdkCri@loDns@blCjy@pyBppA~cC|tCx{EpwDlvG~tBzoDdrA`dC~gAv_Cvw@z|Btr@dkCxq@dtD~XxrCbP|qBlKjqCd@x|C?zt@WzpNf@btEhBdyRtEhtBpLn{ArQppApRtlApVdy@fS|h@~Xty@~tCbhF~dCvrEhoAj}Bdt@rcAls@fbAxeAbdAjyA~gAnuBjiA|oH|xD|xDhtBbeE~pBhdBtbA`vAp{@|r@~q@|wA~qAhoBxsBnrDzoDznJboJ~gArdAf`BrcB`|@xjA`fA`{ArmA~cCjeAtvBb|BxpExuAvtCdbFzgKlvCtgGxhCrsF~uArkC|wAdlBnjB||AtwBrdAj|Brp@htBhLvuBuDteCc\\d`Cq\\dFm@|Dk@lFm@jF}@xnBgXbdAiMdmBgXdlAiM`eBoTlEm@dFk@rEm@|Em@~RiCdcAmJxeB_IflAfDbyAxLtvAdZznAvb@ztAro@faA|i@n}@~r@be@rd@xLhMze@li@nc@~h@r}Ah~BxsKzmOx{Eb}GlfKt}N`nHlgKvjGryIpyBz{CjgBjhCxCdE~CtE~CdE~CtEvCtDfaBpyBdnErrGpkAv`BxyAvtBhgDzyEz}Aj}B|~@pyAx`A~pB~v@dwBrZx_Aba@vvAtn@h}C`a@t_DvYnbE`HnnDT~RjQlcO\\lTd@zU|@zVbArZbB~]xAfYpCz_@`CtZfCzU~CdZzB`RlDfYpCnSfCrP`CdOpCdPnCtOfDrQdiItqb@tj@duCfCbP`CvO`C`QpBdPpBdPbBbPzArQjAtOrAnSrAlUl@bQd@vMl@~RLdPV`RFtP?bPObQOdPe@pR]bQm@pQ{@dP}@tOkA`RgDha@mUbcCce@~`F}Yf~CuTbbCqG`q@mF|i@iGtYuOvlAsAnI{AnHcBbGiBbGyB`HiRng@aC`HaBpGcB`Hu@rGs@jK_@~IUfMm@r[G`zAGpg@Mli@?dvBOzLe@vM}@fNaBhMcBjKqBnIoC~IiCnH_DrGuE|I}Thb@}D`H}EnHkF`HsG`H_IbGuJpGuIdEeKfDwMhCuxAvXuYbFkQhCeYhBsu@hCa]fDkF?uE?mE?cF?mE?}E?oIOgH?}E?oC?gD?gI?{F?gDNcG?{FNsF?uE?mE?eE?mT?mE?kF?}E?eE?uE?yG?mE?eE?sF?eF?{K?sF?cF?gE?mE?cF?uEOmE?kF?cF?gE?sF?kF?uE?{E?mE?mE?mF?sE?eF?kF?uE?mENsF?}DO}E?}E?cF?eE?}E?kF?}EN{E?mE?mF?cF?kF?oD?kF?gEOkFN{F?}D?}E?uE?eE?aH?mJ?cF?eF?mE?{E?{F?sK?eF?uELcF?}ENaM\\mE?uE\\sEN{F\\_ENcF\\sF\\gD^kF\\}El@mEl@}El@kFl@cLxAcF|@mEl@wDl@iGjAwDl@cFjAuEz@qLhCgE|@mEjAcFjAmEjAeEjA}EzAsFhBuD|@gEhB{EzAuEhBuEzA}DzAmEhB}ExBoDlAsExBmEhB_EhBuExBqQ~ImEhCeEhB_EhCeExBeEfC}JbGmEvC}DhCcQxLoDhCmEfDuDvCwDvCuDxC_EfDoDvCuDfD}DfD_EfDuDtDgDxCoDdDoDvDmDfD_EdE_DvDwDtD}DtE_DfD_DvDwDrEgDfEoCdDoDtEoCfDoDtEwCvD_DdEaDtEwCrE_DtEwCdEyCfEmD`GqCdEoCtEwCtEiCtE_DbFiCtEwCrFcLlTaCtEwCdF_D`HwI~RiCbG_CbF{BrFyBdFyBrFyBbG_C`GcBtEiC`HaBbFyBtFkB`GmExMyBpGiBbGkB`GiBtFqBpGkBrFaBbFqBrGsBrFiBbFaC`HiBrFkBdFiBrFyB`GqBtFiC~GiBtEyBrF{BdFgCpGkBtEyBbF_CrFqCrGyBtEiCrFaCrFyBbFwCrFyBtEoCrFqCrFwCdFyBdEqCbF_DdFyBdEwCbFwCdFiCtE_DrEwCtEqCdEwCdFoDtEaCdEgDdEoCtEmEbGiCdDgDtEoCvD_EtE_CvCgDdEgErFgCvC_DvDoDvD_DtDoDvDoDtDuDdE_DvDoDfDwDtDwCfD}DvDwDtD_DxCwDfDeDvCwDfDeEtD_DhCgDvCuEvD_DhC}DfDwDvC}DvCgDhCgEfD}DvC_DhCmEvCgDxBeEfDsPjLwDxBeEvCuEhCoDxB}DfC}DhCgEhCuDxBeEfC_ExBeExBeEhCoDhBuEhCeExBoDjBeEhBeEhCmExBuDxBuExBmEfCoDjBeExBeExBwDhBuExBeExBoDzAsExBwDjBeExBwDxAe_@rQy\\rPw|@td@ewAls@w]rQck@dYaf@zVe_@~Rib@~Sw]bQiR|JgShLc\\nS{PlK{_@lTiaAli@wfAzj@q\\bQ_r@b[c~B|gAymBngAs`@rZuYn^_Zfb@gSxa@mOfc@_Nli@qHvb@cGxa@kFbq@se@rdJes@b`Nql@bbLgh@jhKoXfqFoIx_BqB|}@m@~q@NjiArFfpb@Flj@L`pANdmAThBMhWLtn@dAr~E\\l}Ad@~nCFrz@\\bkDTls@|@vvApBlzCVpg@LrP`HpyK\\`g@^xk@LdP|@huAfShwZ~CldEtEh`JhBnbEjB|rJz@joExCxsK?fd@jAxfDd@dwBzA~_Gz@l`HzA|gKd@zfCFzj@F`f@fCpuOFh~Bd@bf@bBpp@~CflANpH`Rv{ExVzkHvCbp@~IndCxGzhB`Cvm@pLtiDrAro@Vdo@qBxiBgD`q@}Etn@eE`f@uJ|hAiR~yB{e@hpFeUfiCeEjLaCxMwC|IiMdPqM~HcPzAgNkBaMaHaI{KqGwMiCsQe@}T`C_SpHaSnI{KnN_IrK{Azo@pHn]nIn]~HrKhCre@vMld@lKj[bFfc@bG~]fCrQl@lnDhCpf@l@drBLvg@zAz`@^xW?|Dp\\pCzTTfENhBd@lJ?bnBGfXyMM}D?gDm@wC}@qCkAgC{AsBiB_CgDyBuEsAeE{AuEeAcFe@wDMuEOgkAUaI}@_IkAuE{AcFyBeEoCeE_DwD_EiCsFgDiGyBkG]kP?cdBm@uJ?U?","summary":{"length":148.938,"time":4979},"maneuvers":[{"begin_shape_index":0,"length":0.531,"street_names":["IL 251"],"time":0,"type":1,"end_shape_index":9,"instruction":"Go south on South 7th Street\/IL 251. Continue on IL 251.","verbal_post_transition_instruction":"Continue on IL 251 for a half kilometer.","begin_street_names":["South 7th Street","IL 251"],"verbal_pre_transition_instruction":"Go south on South 7th Street, IL 251."},{"begin_shape_index":9,"time":47,"type":18,"end_shape_index":26,"instruction":"Turn right to take the ramp.","length":0.785,"verbal_transition_alert_instruction":"Turn right to take the ramp.","toll":true,"verbal_pre_transition_instruction":"Turn right to take the ramp."},{"verbal_pre_transition_instruction":"Merge onto I 88 West, IL 110 West.","verbal_transition_alert_instruction":"Merge onto I 88 West.","length":30.445,"toll":true,"instruction":"Merge onto I 88 West\/IL 110 West\/Ronald Reagan Memorial Tollway.","end_shape_index":87,"type":25,"time":973,"verbal_post_transition_instruction":"Continue for 30.4 kilometers.","street_names":["I 88 West","IL 110 West","Ronald Reagan Memorial Tollway"],"begin_shape_index":26},{"verbal_pre_transition_instruction":"Make a right U-turn onto I 88 West, IL 110 West.","verbal_transition_alert_instruction":"Make a right U-turn onto I 88 West.","length":0.985,"toll":true,"instruction":"Make a right U-turn onto I 88 West\/IL 110 West\/Ronald Reagan Memorial Tollway.","end_shape_index":92,"type":12,"time":31,"verbal_post_transition_instruction":"Continue for 1 kilometer.","street_names":["I 88 West","IL 110 West","Ronald Reagan Memorial Tollway"],"begin_shape_index":87},{"verbal_pre_transition_instruction":"Make a right U-turn onto I 88 West, IL 110 West.","verbal_transition_alert_instruction":"Make a right U-turn onto I 88 West.","length":88.888,"toll":true,"instruction":"Make a right U-turn onto I 88 West\/IL 110 West.","end_shape_index":460,"type":12,"time":2845,"verbal_post_transition_instruction":"Continue for 88.9 kilometers.","street_names":["I 88 West","IL 110 West"],"begin_shape_index":92},{"begin_shape_index":460,"time":24,"type":20,"end_shape_index":478,"instruction":"Take exit 1B on the right toward I80\/I74\/ Des Moines.","length":0.593,"verbal_transition_alert_instruction":"Take exit 1B on the right.","verbal_pre_transition_instruction":"Take exit 1B on the right toward I80, I74."},{"begin_shape_index":478,"time":41,"type":23,"end_shape_index":506,"instruction":"Keep right at the fork.","length":1.083,"verbal_transition_alert_instruction":"Keep right at the fork.","verbal_pre_transition_instruction":"Keep right at the fork."},{"begin_shape_index":506,"street_names":["I 80 West"],"verbal_post_transition_instruction":"Continue for 22.9 kilometers.","time":798,"type":25,"end_shape_index":931,"instruction":"Merge onto I 80 West.","length":22.938,"verbal_transition_alert_instruction":"Merge onto I 80 West.","verbal_pre_transition_instruction":"Merge onto I 80 West."},{"begin_shape_index":931,"time":20,"type":20,"end_shape_index":949,"instruction":"Take exit 295A on the right.","length":0.539,"verbal_transition_alert_instruction":"Take exit 295A on the right.","verbal_pre_transition_instruction":"Take exit 295A on the right."},{"begin_shape_index":949,"street_names":["US 61 Business"],"verbal_post_transition_instruction":"Continue for 1.2 kilometers.","time":49,"type":25,"end_shape_index":964,"instruction":"Merge onto US 61 Business.","length":1.247,"verbal_transition_alert_instruction":"Merge onto US 61 Business.","verbal_pre_transition_instruction":"Merge onto US 61 Business."},{"begin_shape_index":964,"street_names":["West 65th Street"],"verbal_post_transition_instruction":"Continue for 300 meters.","time":25,"type":10,"end_shape_index":971,"instruction":"Turn right onto West 65th Street.","length":0.281,"verbal_transition_alert_instruction":"Turn right onto West 65th Street.","verbal_pre_transition_instruction":"Turn right onto West 65th Street."},{"begin_shape_index":971,"street_names":["Frontage Road"],"verbal_post_transition_instruction":"Continue for 600 meters.","time":89,"type":10,"end_shape_index":1001,"instruction":"Turn right onto Frontage Road.","length":0.623,"verbal_transition_alert_instruction":"Turn right onto Frontage Road.","verbal_pre_transition_instruction":"Turn right onto Frontage Road."},{"begin_shape_index":1001,"time":0,"type":4,"end_shape_index":1001,"instruction":"You have arrived at your destination.","length":0.000,"verbal_transition_alert_instruction":"You will arrive at your destination.","verbal_pre_transition_instruction":"You have arrived at your destination."}]}],"units":"kilometers","summary":{"length":148.938,"time":4979},"locations":[{"lon":-89.068802,"lat":41.906700,"type":"break"},{"lon":-90.571503,"lat":41.589298,"type":"break"}]}}

**Comment by gknisely** [comment]
Hey Rhonda, 
I am not seeing this issue.  So, I am assuming that it was a data issue that was fixed?  Can you confirm that everything is ok?

![image](https://cloud.githubusercontent.com/assets/2676277/9643911/6a722498-5192-11e5-9e24-19ad5c25417a.png)

**Comment by rmglennon** [comment]
@gknisely Thanks for checking -- closing this. Must have been fixed in the course of some other updates (not seeing any recent changesets in OSM for these features). The Valhalla route now goes straight through without suggesting a u-turn.
