### ISSUE TITLE
Overflow while updating destinations in TimeDistanceMatrix

### ISSUE THREAD

**Issue by ptpt** [valhalla/thor#243]
https://github.com/valhalla/thor/blob/41cd98460fde27c740f9f0e2511118a068ea5182/src/thor/timedistancematrix.cc#L534

If that destination is at the same edge with the origin but behind the origin i.e. `dest.id == origin.id && dest.dist < origin.dist`, `edge->length() * (1.f - dest.dist)` will be larger than `pred.walking_distance()` which is `edge->length() * (1.f - origin.dist)`. Negative result causes overflow.

**Comment by dnesbitt61** [comment]
Thanks for the info. I hope to clean up the "edge" cases within time distance methods to handle cases where is destination is along the same edge. I knew it was TODO and hope to get to it today.

**Comment by dnesbitt61** [comment]
Let me know if you still see issues. I ran a few test cases that seemed OK. We will put this under more testing as we look to expose it in our service API.
