### ISSUE TITLE
Weird looking route (detour)

### ISSUE THREAD

**Issue by fnicollet** [valhalla/thor#245]
Hello,

As I was trying out the API with the sample page, I tried this one:  36.442 , -119.95 , 35.778 , -119.467
Which gave me:
![image](https://cloud.githubusercontent.com/assets/1240481/10343832/38019c24-6d20-11e5-8090-b3d0ee76c3df.png)

The detour in the bottom-right corner looks strange, might be interesting to investigate

Fabien

**Comment by dnesbitt61** [comment]
Will be part of our next release to the Mapzen turn by turn service.
