### ISSUE TITLE
Odd footpath - requires per country pedestrian access logic

### ISSUE THREAD

**Issue by ptpt** [valhalla/thor#277]
[http://valhalla.github.io/demos/routing/#loc=12,52.168352,5.437374&locations=[{"lat":52.176458200914624,"lng":5.388337969779968},{"lat":52.10734865208675,"lng":5.396234393119812}]&costing="auto"](http://valhalla.github.io/demos/routing/#loc=12,52.168352,5.437374&locations=[{"lat":52.176458200914624,"lng":5.388337969779968},{"lat":52.10734865208675,"lng":5.396234393119812}]&costing="auto")

![screenshot from 2015-12-09 17-34-05](https://cloud.githubusercontent.com/assets/87357/11691459/502ae722-9e9b-11e5-9f4d-b6f00bfdfca2.png)

**Comment by gknisely** [comment]
By default cycleways have pedestrian access turned off.  This design is correct; however, we need to implement default access restrictions per country.  The logic would allow pedestrian access to way https://www.openstreetmap.org/edit#map=19/52.17403/5.37836 and then this would in turn provide the correct walking route.  Please see http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions#The_Netherlands
