### ISSUE TITLE
Bad route thru off-ramp / on-ramp back onto highway in Phoenix

### ISSUE THREAD

**Issue by nvkelso** [valhalla/thor#317]
I hit this using master-907, and can replicate it in the routing demo:

http://valhalla.github.io/demos/routing/#loc=16,33.537764,-112.034873&locations=[{"lat":33.43659851558681,"lon":-112.0111083984375},{"lat":33.59503207294312,"lon":-112.02801704406738}]&costing="auto"

This entire block is in error, I shouldn't have been directed off the highway to get back on the highway:

```
8: Take exit 5 on the right toward East Glendale Avenue/ East Lincoln Drive.
VERBAL_ALERT: Take exit 5 on the right.
VERBAL_PRE: Take exit 5 on the right toward East Glendale Avenue, East Lincoln Drive.
322 m
9: Stay straight to take the ramp toward East Glendale Avenue/ East Lincoln Drive.
VERBAL_ALERT: Stay straight to take the ramp toward East Glendale Avenue.
VERBAL_PRE: Stay straight to take the ramp toward East Glendale Avenue, East Lincoln Drive.
62 m
10: Keep left toward East Glendale Avenue/ East Lincoln Drive.
VERBAL_ALERT: Keep left toward East Glendale Avenue.
VERBAL_PRE: Keep left toward East Glendale Avenue, East Lincoln Drive.
94 m
11: Continue.
VERBAL_ALERT: Continue.
VERBAL_PRE: Continue for 10 meters.
10 m
12: Turn right.
VERBAL_ALERT: Turn right.
VERBAL_PRE: Turn right.
VERBAL_POST: Continue for less than 10 meters.
9 m
13: Stay straight to take the ramp toward North Arizona SR-51.
VERBAL_ALERT: Stay straight to take the ramp toward North Arizona State Route 51.
VERBAL_PRE: Stay straight to take the ramp toward North Arizona State Route 51.
71 m
14: Stay straight to take the ramp toward North Arizona SR-51.
VERBAL_ALERT: Stay straight to take the ramp toward North Arizona State Route 51.
VERBAL_PRE: Stay straight to take the ramp toward North Arizona State Route 51.
575 m
15: Merge onto AZ 51 North/Piestewa Freeway/Squaw Peak Parkway.
VERBAL_ALERT: Merge onto Arizona 51 North.
VERBAL_PRE: Merge onto Arizona 51 North, Piestewa Freeway.
VERBAL_POST: Continue for 6.6 kilometers.
```

<img width="491" alt="screen shot 2016-02-15 at 15 32 54" src="https://cloud.githubusercontent.com/assets/853051/13062154/a2190134-d3f9-11e5-9955-51d95995720c.png">

**Comment by kevinkreiser** [comment]
playing around with routing right there it seems to lose connectivity under the bridge. looking at the attribution i cant see why but something is fishy with either the data or the way its being interpreted in `mjolnir`

**Comment by kevinkreiser** [comment]
scratch that its not fishy, we have a bug here: https://github.com/valhalla/conf/blob/master/edges.lua#L766

the tunnel is marked as `area=no` and we throw away anything with the area tag at all which is totally bogus. fixing now...

**Comment by kevinkreiser** [comment]
this is fixed!
