### ISSUE TITLE
Support ways as via elements in restrictions

### ISSUE THREAD

**Issue by RicoElectrico** [valhalla/thor#329]
Some restrictions can only be modeled this way. Example: https://www.openstreetmap.org/relation/2699206

**Comment by dnesbitt61** [comment]
Thanks, hope to get to this shortly.

**Comment by dnesbitt61** [comment]
Added complex restrictions to the data (includes these via-way restrictions) and avoid them in path algorithms.

**Comment by RicoElectrico** [comment]
A HUGE thank you! :heart: Many OSM routing engines ignore such restriction, whereas routing cannot be complete without them.

**Comment by gknisely** [comment]
@RicoElectrico you are so welcome.  :smile:

**Comment by RicoElectrico** [comment]
Can you give an ETA when this will be available in the online routing of Mapzen?

**Comment by gknisely** [comment]
@RicoElectrico This has been released.  Are you seeing an issue?  Can you provide a link to the restriction?

**Comment by RicoElectrico** [comment]
Oops. My fault. :P So I can confirm. It works fine.

**Comment by gknisely** [comment]
Ok great!  Had me worried there for a second.  :smile:
