### ISSUE TITLE
Replace TimeDistanceMatrix with CostMatrix

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/thor#366]
Use CostMatrix for one-to-many, many-to-one, and many-to-many matrix calls.

**Comment by antoniomedrano** [comment]
Does this mean now that route and many_to_many should give the same results now? When did this take effect on master?

**Comment by dnesbitt61** [comment]
They should be closer than what they were. This change was made in June. There still may be some slight differences based on hierarchy transitions, but more recent changes were made to try to make the transition logic consistent. In general though I think the times and distances should be pretty close between matrix and route.
