### ISSUE TITLE
Cross country borders of India

### ISSUE THREAD

**Issue by nisarg09** [valhalla/thor#376]
International borders of India are not drawn correctly. When I put inputs as two different cities of two different countries around India they are showing route from some of the places through India. Kindly check it.

**Comment by gknisely** [comment]
Hi @nisarg09 

Can you provide an example of your issue?  Also, can you describe the problem a little more?  Do you want your route to stay within India?

Thanks.

--Greg.

**Comment by dnesbitt61** [comment]
Closing this issue. Please open another issue with a route example that illustrates the issue.
