### ISSUE TITLE
Clarify time zone in date_time

### ISSUE THREAD

**Issue by danvk** [valhalla/thor#389]
The [API docs][1] say:

> date_time = (response only) Expected date/time for the user to be at the location using the ISO 8601 format (YYYY-MM-DDThh:mm). For example “2015-12-29T08:00”.

It would be helpful for this to say something about time zones. For example, is that 8 AM UTC? Local time for the route? Local time for the computer generating the route? Also an example of how to set the time zone explicitly, e.g. "2015-12-29T08:00-0400".

[1]: https://mapzen.com/documentation/turn-by-turn/api-reference/#inputs-of-a-route

**Comment by gknisely** [comment]
Dan,

It is the date/time at that particular location for the route.    We do not
allow a user to set a timezone, but we do allow you to set the date/time to
start at or arrive by for the route.

https://mapzen.com/documentation/turn-by-turn/api-reference/#other-request-options

Let me know if you have more questions.

  --Greg

**Comment by danvk** [comment]
Thanks for the clarification.

The docs would be much clearer if they read:

> value - the date and time is specified in ISO 8601 format (YYYY-MM-DDThh:mm) **in the local time zone of departure**. For example “2016-07-03T08:06”

While the ISO 8601 spec does say that no time zone specifier indicates local time, there are many possibilities for what "local" means in this context.

**Comment by dnesbitt61** [comment]
We will investigate adding the timezone to the response and will update the documentation.

**Comment by gknisely** [comment]
@danvk we have updated the documentation and we also now return the timezone offset at the locations

Thanks.
--Greg
