### ISSUE TITLE
U-tuns in optimized routing

### ISSUE THREAD

**Issue by ptpt** [valhalla/thor#420]
This issue is brough by the discussion with @dnesbitt61  at https://github.com/valhalla/meili/issues/36

Should we disallow the U-turn at point 1?

http://valhalla.github.io/demos/optimized_route/#loc=18,40.851307,-73.991649&locations=[{"lat":40.850777,"lon":-73.991826},{"lat":40.851362,"lon":-73.992834},{"lat":40.850546,"lon":-73.992936}]&costing="auto"
![image](https://cloud.githubusercontent.com/assets/87357/17813940/c9f8a756-662d-11e6-83fe-8e24a904a128.png)

**Comment by dnesbitt61** [comment]
Each location in an optimized route is thought of as a "break" or stop, not a "through" or via location. So between each 2 stops it is considered a separate leg of the route.

**Comment by ptpt** [comment]
I see the difference now. In meili GPS locations are treated as "via" locations.

Thanks for the explanation!
