### ISSUE TITLE
An Extra loop being made in route in Cleveland, OH

### ISSUE THREAD

**Issue by skorasaurus** [valhalla/thor#461]
Hi, 

While using lrm-mapzen locally, I found an odd route. 

The url is: https://valhalla.mapzen.com/route?json={%22locations%22:[{%22lat%22:41.437734,%22lon%22:-81.699389,%22type%22:%22break%22},{%22lat%22:41.488665,%22lon%22:-81.648306,%22type%22:%22break%22}],%22costing%22:%22auto%22}&api_key=valhalla-PVA4Y8g

As shown in ![selection_082](https://cloud.githubusercontent.com/assets/955351/20070074/1c08177c-a4ed-11e6-90d4-0cb626c74540.png), 
The step immediately following "Turn left onto East 55th Street.', should be 'Turn right onto Woodland Avenue/SR 87' instead of making a loop.  I'm familiar with the area, have driven on it and am sure it's the proper and legal route. 

At the suggestion of @kkowalsky , I'm reporting this here. 

Sorry for the vague title, I haven't had the time to investigate if there's any other similar intersections where a similar behavior occurs.

**Comment by kevinkreiser** [comment]
@skorasaurus we'll have a look, thanks for pointing it out! for reference here is an interactive link to play around with:

http://valhalla.github.io/demos/routing/#loc=14,41.468039,-81.654124&locations=[{%22lat%22:41.437734,%22lon%22:-81.699389,%22type%22:%22break%22},{%22lat%22:41.488665,%22lon%22:-81.648306,%22type%22:%22break%22}]&costing=%22auto%22

i'm currently not sure what is causing this yet, @dnesbitt61 and i will take a look

**Comment by dnesbitt61** [comment]
Appears to be fixed with our Valhalla 2.0 release. Please reopen if you see this or a similar issue.
